nom_etudiant = (input("Nom de l'utilisateur?"))
note_tp1 = int(input("Note de l'utilisateur au TP1? (sur 10)"))
note_tp2 = int(input("Note de l'utilisateur au TP2? (sur 10)"))
examen_1 = int(input("Note de l'utilisateur à l'examen 1? (sur 100)?"))
examen_2 = int(input("Note de l'utilisateur à l'examen 2? (sur 100)?"))
note_finale = (10*0.20*note_tp1)+(10*.30*note_tp2)+(0.20*examen_1)+(0.30*examen_2)
print()
print(f"Étudiant : {nom_etudiant}")
print(f"Note au TP1 (20% sur 10pts) : {note_tp1}")
print(f"Note au TP2 (30% sur 10 pts): {note_tp2}")
print(f"Note examen #1 (20% sur 100pts) : {examen_1}")
print(f"Note examen #2 (30% sur 100pts): {examen_2}")
print(f"Note obtenue pour ce cours : {note_finale}/100")
print("Attention, l'application de la double sanction n'a pas été réalisée!")